sync_pairs:
  - source: C:\Users\willi\Downloads
    target: \\tower\tools\backups\Downloads
  - source: C:\Users\willi\Documents
    target: \\tower\tools\backups\Documents

ignore:
  - "*.tmp"
  - "temp/*"
  - ".git/*"
  - "*.crdownload"